CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(10) NOT NULL CHECK (role IN ('USER', 'ADMIN')),
  cep VARCHAR(8) NOT NULL,
  city VARCHAR(120) NOT NULL,
  uf VARCHAR(2) NOT NULL
);

CREATE TABLE services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL REFERENCES users(id),
  title VARCHAR(160) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(80) NOT NULL,
  price NUMERIC(12,2) NOT NULL CHECK (price > 0),
  status VARCHAR(15) NOT NULL CHECK (status IN ('ATIVO', 'PAUSADO', 'ENCERRADO'))
);
CREATE INDEX idx_services_provider ON services(provider_id);
CREATE INDEX idx_services_status ON services(status);

CREATE TABLE contracts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT NOT NULL REFERENCES services(id),
  customer_id BIGINT NOT NULL REFERENCES users(id),
  status VARCHAR(15) NOT NULL CHECK (status IN ('SOLICITADA', 'ACEITA', 'CONCLUIDA', 'CANCELADA')),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_contracts_service ON contracts(service_id);
CREATE INDEX idx_contracts_customer ON contracts(customer_id);
